# Generated by Django 6.0.6 on 2026-08-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_userwarning'),
        ('posts', '0004_post_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwarning',
            name='reported_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_warnings', to='posts.post'),
        ),
    ]
