# Generated by Django 6.0.6 on 2026-10-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_userwarning_reported_post'),
        ('posts', '0004_post_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post'),
        ),
    ]
