# Generated by Django 6.0.6 on 2026-08-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('FOLLOW', 'Follow'), ('MESSAGE', 'Message'), ('MODERATION_WARNING', 'Moderation Warning')], max_length=30),
        ),
    ]
